import React from 'react'

export const data = [
  {
    easypay_merchant_id: '1',
    retailer_id: '102',
    merchant_name: 'perungudi',
    merchant_adress: 'chennai',
    state: 'tamil nadu',
    city: 'vellore',
    qr_code: '7689cbdbi',
    dmo_status: 'active',
  },
  {
    easypay_merchant_id: '2',
    dmo_id: 'D2',
    merchant_name: 'kandanchavadi',
    merchant_adress: 'Banglore',
    state: 'tamil nadu',
    city: 'chennai',
    qr_code: 'hedd7898ued',
    dmo_status: 'active',
  },
  {
    easypay_merchant_id: '3',
    dmo_id: 'D3',
    merchant_name: 'siruseri',
    merchant_adress: 'Goa',
    state: 'mharastra',
    city: 'panzi',
    qr_code: 'swdwddw534',
    dmo_status: 'active',
  },
  {
    easypay_merchant_id: '4',
    dmo_id: 'D4',
    merchant_name: 'navalur',
    merchant_adress: 'kolkata',
    state: 'west bangal',
    city: 'kolkata',
    qr_code: '357rtuyf56',
    dmo_status: 'active',
  },
  {
    easypay_merchant_id: '5',
    dmo_id: 'D5',
    merchant_name: 'thoraipakkam',
    merchant_adress: 'combatour',
    state: 'andhra',
    city: 'malapakkam',
    qr_code: '789hgfty',
    dmo_status: 'active',
  },
  {
    easypay_merchant_id: '6',
    dmo_id: 'D6',
    merchant_name: 'kottivakam',
    merchant_adress: 'madurai',
    state: 'karanataka',
    city: 'banglore',
    qr_code: '35798wer90',
    dmo_status: 'active',
  },
  {
    easypay_merchant_id: '7',
    dmo_id: 'D7',
    merchant_name: 'sholinganur',
    merchant_adress: 'chennai',
    state: 'Tamil nadu',
    city: 'chennai',
    qr_code: '98764tyuu',
    dmo_status: 'active',
  }
]

export default data