export const organizationData = [
    {
        id: "1001",
        // "org_name": "Infinity Hospitality",
        // "org_type": "partnership",
        // "outlets_count": "5",
        // "kyc_status": "verified",
        // "org_status": "Active",
        // "pan_no": "AAFFI2896H",
        // "cin_no": "29521276149"
        organizationName: 'Infinity Hospitality',
        organizationType: 'partnership',
        incorporationDate: '12/05/2019',
        cinNumber: '29521276149',
        panNumber: 'AAFFI2896H',
        outletsCount: 0,
        selectedKycIdx: 'true',
        GSTNumber: '8123798127389123',
        selectedOrganizationStatusIdx: 'true',
        organizationAddress: 'Adayar',
        city: 'Chennai',
        selectedCityIdx: 2,
        state: 'Tamilnadu',
        selectedStateIdx: 1,
        pincode: '600086',
        landlineNo: '044 4356782',
        authorizedPerson: 'Madhan',
        mobileNo: '1234567890',
        email: 'abc@gmailcom',
        
        photo: true,
        pancard: false,
        address: false,
        
        partnershipPancard: true,
        partnershipDeed: false,
        partnershipLOA: false,
    
        pvtPancard: true,
        pvtCOI: false,
        pvtLOA: false,
    },
    {
        id: "1002",
        // "org_name": "M/S.Contessa Wines",
        // "org_type": "partnership",
        // "outlets_count": "5",
        // "kyc_status": "verified",
        // "org_status": "Active",
        // "pan_no": "AAFFI2896H",
        // "cin_no": "29521276149"
        organizationName: 'M/S.Contessa Wines',
        organizationType: 'partnership',
        incorporationDate: '12/05/2019',
        cinNumber: '29521276149',
        panNumber: 'AAFFI2896H',
        outletsCount: 0,
        selectedKycIdx: 'true',
        GSTNumber: '8123798127389123',
        selectedOrganizationStatusIdx: 'true',
        organizationAddress: 'Adayar',
        city: 'Chennai',
        selectedCityIdx: 1,
        state: 'Tamilnadu',
        selectedStateIdx: 1,
        pincode: '600086',
        landlineNo: '044 4356782',
        authorizedPerson: 'Madhan',
        mobileNo: '1234567890',
        email: 'abc@gmailcom',
        
        photo: true,
        pancard: false,
        address: false,
        
        partnershipPancard: true,
        partnershipDeed: false,
        partnershipLOA: false,
    
        pvtPancard: true,
        pvtCOI: false,
        pvtLOA: false,
    },
    {
        id: "1003",
        // "org_name": "Pink Panther Hospitality Pvt Ltd",
        // "org_type": "partnership",
        // "outlets_count": "5",
        // "kyc_status": "verified",
        // "org_status": "Active",
        // "pan_no": "AAFFI2896H",
        // "cin_no": "29521276149"  
        organizationName: 'Pink Panther Hospitality Pvt Ltd',
        organizationType: 'partnership',
        incorporationDate: '12/05/2019',
        cinNumber: '29521276149',
        panNumber: 'AAFFI2896H',
        outletsCount: 0,
        selectedKycIdx: 'true',
        GSTNumber: '8123798127389123',
        selectedOrganizationStatusIdx: 'true',
        organizationAddress: 'Adayar',
        city: 'Chennai',
        selectedCityIdx: 1,
        state: 'Tamilnadu',
        selectedStateIdx: 1,
        pincode: '600086',
        landlineNo: '044 4356782',
        authorizedPerson: 'Madhan',
        mobileNo: '1234567890',
        email: 'abc@gmailcom',
        
        photo: true,
        pancard: false,
        address: false,
        
        partnershipPancard: true,
        partnershipDeed: false,
        partnershipLOA: false,
    
        pvtPancard: true,
        pvtCOI: false,
        pvtLOA: false,
    },
    {
        id: "1004",
        // "org_name": "abccdefg",
        // "org_type": "partnership",
        // "outlets_count": "5",
        // "kyc_status": "verified",
        // "org_status": "Active",
        // "pan_no": "AAFFI2896H",
        // "cin_no": "29521276149"
        organizationName: 'abccdefg',
        organizationType: 'partnership',
        incorporationDate: '12/05/2019',
        cinNumber: '29521276149',
        panNumber: 'AAFFI2896H',
        outletsCount: 0,
        selectedKycIdx: 'false',
        GSTNumber: '8123798127389123',
        selectedOrganizationStatusIdx: 'true',
        organizationAddress: 'Adayar',
        city: 'Chennai',
        selectedCityIdx: 1,
        state: 'Tamilnadu',
        selectedStateIdx: 1,
        pincode: '600086',
        landlineNo: '044 4356782',
        authorizedPerson: 'Madhan',
        mobileNo: '1234567890',
        email: 'abc@gmailcom',
        
        photo: true,
        pancard: false,
        address: false,
        
        partnershipPancard: true,
        partnershipDeed: false,
        partnershipLOA: false,
    
        pvtPancard: true,
        pvtCOI: false,
        pvtLOA: false,
    },
    {
        id: "1005",
        // "org_name": "Insight Hospitality Pvt Ltd",
        // "org_type": "proprietorship",
        // "outlets_count": "5",
        // "kyc_status": "verified",
        // "org_status": "Active",
        // "pan_no": "AAFFI2896H",
        // "cin_no": "29521276149"
        organizationName: 'Insight Hospitality Pvt Ltd',
        organizationType: 'partnership',
        incorporationDate: '12/05/2019',
        cinNumber: '29521276149',
        panNumber: 'AAFFI2896H',
        outletsCount: 0,
        selectedKycIdx: 'true',
        GSTNumber: '8123798127389123',
        selectedOrganizationStatusIdx: 'true',
        organizationAddress: 'Adayar',
        city: 'Chennai',
        selectedCityIdx: 1,
        state: 'Tamilnadu',
        selectedStateIdx: 1,
        pincode: '600086',
        landlineNo: '044 4356782',
        authorizedPerson: 'Madhan',
        mobileNo: '1234567890',
        email: 'abc@gmailcom',
        
        photo: true,
        pancard: false,
        address: false,
        
        partnershipPancard: true,
        partnershipDeed: false,
        partnershipLOA: false,
    
        pvtPancard: true,
        pvtCOI: false,
        pvtLOA: false,
    },
    {
        id: "1006",
        // "org_name": "abccdefg",
        // "org_type": "pvtltd",
        // "outlets_count": "5",
        // "kyc_status": "verified",
        // "org_status": "Active",
        // "pan_no": "AAFFI2896H",
        // "cin_no": "29521276149"
        organizationName: 'abccdefg',
        organizationType: 'partnership',
        incorporationDate: '12/05/2019',
        cinNumber: '29521276149',
        panNumber: 'AAFFI2896H',
        outletsCount: 0,
        selectedKycIdx: 'false',
        GSTNumber: '8123798127389123',
        selectedOrganizationStatusIdx: 'true',
        organizationAddress: 'Adayar',
        city: 'Chennai',
        selectedCityIdx: 1,
        state: 'Tamilnadu',
        selectedStateIdx: 1,
        pincode: '600086',
        landlineNo: '044 4356782',
        authorizedPerson: 'Madhan',
        mobileNo: '1234567890',
        email: 'abc@gmailcom',
        
        photo: true,
        pancard: false,
        address: false,
        
        partnershipPancard: true,
        partnershipDeed: false,
        partnershipLOA: false,
    
        pvtPancard: true,
        pvtCOI: false,
        pvtLOA: false,
    }
]

export const retailerData = [
    {
        id: '1001',
        // retailerName: 'Contessa Wines',
        // retailerAddress: 'No 127/1, 1st Main Road, Sheshadripuram',
        // retailerStatus: 'active',
        // state: 'Tamilnadu',
        // city: 'Chennai',
        retailerStatus: 'active',

        //organizationName: '',
        selectedOrganizationIdx: 1,
        ksbclCode: '123456',
        outletName: 'Contessa Wines',
        exciseLicenseNo: '1236799',
        discountPercent: '12',
        deliveryDiscountPercent: '10',
        serviceChargePercent: '12',
        //KYCVerified: '',
        selectedKycIdx: 'false',
        selectedOutletStatusIdx: 'true',
        FSSAINumber:'45454545',
    
        city: 'Chennai',
        selectedCityIdx: 1,
        state: 'Tamilnadu',
        selectedStateIdx: 1,
        pincode: '600086',
        outletAddress: 'No 127/1, 1st Main Road, Sheshadripuram',
        landlineNo: '3456789',
        gpsCoordinates: '12,13',
        mobileNo: '1234567890',
        email: 'abc@gmail.com',
        
        bankName: 'SBI',
        accountHolderName: 'xxx',
        accountNumber: '123456789',
        branch: 'Adayar',
        accountType: 'savings',
        IFSC: 'SBIN0038',
        cancelledCheck: true,
        exciseLicense: false,
        outletPhoto: false,
    },
    {
        id: '1002',
        // retailerName: 'Metro Spirit',
        // retailerAddress: 'No 60/3, 3rd Phase, Nagappa Layout, Vidyaranyapura Post',
        retailerStatus: 'inactive',
        // state: 'Tamilnadu',
        // city: 'Chennai'
        //organizationName: '',
        selectedOrganizationIdx: 1,
        ksbclCode: '123456',
        outletName: 'Metro Spirit',
        exciseLicenseNo: '1236799',
        discountPercent: '12',
        deliveryDiscountPercent: '10',
        serviceChargePercent: '12',
        //KYCVerified: '',
        selectedKycIdx: "false",
        selectedOutletStatusIdx: "true",
        FSSAINumber:'45454545',
    
        city: 'Chennai',
        selectedCityIdx: 1,
        state: 'Tamilnadu',
        selectedStateIdx: 1,
        pincode: '600086',
        outletAddress: 'No 60/3, 3rd Phase, Nagappa Layout, Vidyaranyapura Post',
        landlineNo: '3456789',
        gpsCoordinates: '12,13',
        mobileNo: '1234567890',
        email: 'abc@gmail.com',
        
        bankName: 'SBI',
        accountHolderName: 'xxx',
        accountNumber: '123456789',
        branch: 'Adayar',
        accountType: 'savings',
        IFSC: 'SBIN0038',
        cancelledCheck: false,
        exciseLicense: false,
        outletPhoto: false,
    },
    {
        id: '1003',
        // retailerName: 'Santhosh Wines',
        // retailerAddress: 'No 1788/C, 9th Cross, 5th Main, Hampi Nagar, R P C Layout',
        retailerStatus: 'active',
        // state: 'Tamilnadu',
        // city: 'Chennai'
        selectedOrganizationIdx: 1,
        ksbclCode: '123456',
        outletName: 'Santhosh Wines',
        exciseLicenseNo: '1236799',
        discountPercent: '12',
        deliveryDiscountPercent: '10',
        serviceChargePercent: '12',
        //KYCVerified: '',
        selectedKycIdx: "true",
        selectedOutletStatusIdx: "true",
        FSSAINumber:'45454545',
    
        city: 'Chennai',
        selectedCityIdx: 1,
        state: 'Tamilnadu',
        selectedStateIdx: 1,
        pincode: '600086',
        outletAddress: 'No 1788/C, 9th Cross, 5th Main, Hampi Nagar, R P C Layout',
        landlineNo: '3456789',
        gpsCoordinates: '12,13',
        mobileNo: '1234567890',
        email: 'abc@gmail.com',
        
        bankName: 'SBI',
        accountHolderName: 'xxx',
        accountNumber: '123456789',
        branch: 'Adayar',
        accountType: 'savings',
        IFSC: 'SBIN0038',
        cancelledCheck: false,
        exciseLicense: false,
        outletPhoto: false,
    },
    {
        id: '1004',
        // retailerName: 'Venkateshwara Wines',
        // retailerAddress: 'No 2, 1st Stage, 5th Phase, West Of Chord Road, Rajajinagar',
        retailerStatus: 'active',
        // state: 'Tamilnadu',
        // city: 'Chennai'
        selectedOrganizationIdx: 1,
        ksbclCode: '123456',
        outletName: 'Venkateshwara Wines',
        exciseLicenseNo: '1236799',
        discountPercent: '12',
        deliveryDiscountPercent: '10',
        serviceChargePercent: '12',
        //KYCVerified: '',
        selectedKycIdx: "true",
        selectedOutletStatusIdx: "true",
        FSSAINumber:'45454545',
    
        city: 'Chennai',
        selectedCityIdx: 1,
        state: 'Tamilnadu',
        selectedStateIdx: 1,
        pincode: '600086',
        outletAddress: 'No 2, 1st Stage, 5th Phase, West Of Chord Road, Rajajinagar',
        landlineNo: '3456789',
        gpsCoordinates: '12,13',
        mobileNo: '1234567890',
        email: 'abc@gmail.com',
        
        bankName: 'SBI',
        accountHolderName: 'xxx',
        accountNumber: '123456789',
        branch: 'Adayar',
        accountType: 'savings',
        IFSC: 'SBIN0038',
        cancelledCheck: false,
        exciseLicense: false,
        outletPhoto: false,
    },
    {
        id: '1005',
        // retailerName: 'Takkes Wines Center',
        // retailerAddress: 'No 10, 8th Cross Malleswaram',
        retailerStatus: 'active',
        // state: 'Tamilnadu',
        // city: 'Chennai'
        selectedOrganizationIdx: 1,
        ksbclCode: '123456',
        outletName: 'Takkes Wines Center',
        exciseLicenseNo: '1236799',
        discountPercent: '12',
        deliveryDiscountPercent: '10',
        serviceChargePercent: '12',
        //KYCVerified: '',
        selectedKycIdx: "true",
        selectedOutletStatusIdx: "true",
        FSSAINumber:'45454545',
    
        city: 'Chennai',
        selectedCityIdx: 1,
        state: 'Tamilnadu',
        selectedStateIdx: 1,
        pincode: '600086',
        outletAddress: 'No 10, 8th Cross Malleswaram',
        landlineNo: '3456789',
        gpsCoordinates: '12,13',
        mobileNo: '1234567890',
        email: 'abc@gmail.com',
        
        bankName: 'SBI',
        accountHolderName: 'xxx',
        accountNumber: '123456789',
        branch: 'Adayar',
        accountType: 'savings',
        IFSC: 'SBIN0038',
        cancelledCheck: false,
        exciseLicense: false,
        outletPhoto: false,
    }
]